VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FileHandler"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'   //TODO: Move username / environ functions here
'   //FEATURE: Get all files from a particular directory
'   //FEATURE: Search for files or directory name in a particular directory